SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Color](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](32) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Color] ADD  CONSTRAINT [PK_Color] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Shirt](
	[Id] [int] NOT NULL,
	[Color] [nvarchar](50) NULL,
	[Size] [int] NULL,
	[Color_Id] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Shirt] ADD  CONSTRAINT [PK_Shirt] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Shirt]  WITH CHECK ADD  CONSTRAINT [FK_Shirt_Color] FOREIGN KEY([Color_Id])
REFERENCES [dbo].[Color] ([Id])
GO
ALTER TABLE [dbo].[Shirt] CHECK CONSTRAINT [FK_Shirt_Color]
GO
